djangotutorial/djangotutorial/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('get_object_or_404.urls')),
]

djangotutorial/get_object_or_404/urls.py
from django.urls import path
from .views import home, post_detail

app_name="posts"

urlpatterns = [
    path('', home, name='home'),
    path('posts/<int:pk>/', post_detail,name='post_detail')

]

djangotutorial/get_object_or_404/models.py
from django.db import models

class Post(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()

    def __str__(self):
        return self.title

djangotutorial/get_object_or_404/views.py
from django.shortcuts import render, get_object_or_404
from django.http import Http404
from .models import Post

def home(request):
    posts = Post.objects.all()

    return render(request, 'posts/allposts.html',{'posts': posts})

def post_detail(request, pk):
    # try:
    #     post = Post.objects.get(id=pk)
    # except Post.DoesNotExist:
    #     raise Http404("Given query is not found")
    
    post = get_object_or_404(Post, pk=pk)
      
    return render(request, 'posts/post_detail.html', {'post': post})

djangotutorial/get_object_or_404/templates/posts/allposts.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>All Posts</title>
   
</head>
<body>
    <h1>All Posts</h1>
    {% if posts %}
        {% for post in posts %}
            <div>
                <h2><a href="{% url 'posts:post_detail' post.id %}">{{ post.title }}</a></h2>
                <p>{{ post.description }}</p>
            </div>
        {% endfor %}
    {% else %}
        <p>No posts available.</p>
    {% endif %}
</body>
</html>

djangotutorial/get_object_or_404/templates/posts/post_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ post.title }}</title>
</head>
<body>
    <div class="container">
        <h1>{{ post.title }}</h1>
        <p>{{ post.description }}</p>
    </div>
</body>
</html>